name: Test

on:
    pull_request:
        branches:
            - "master"

jobs:
    tox-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  pip install -r requirements_dev.txt
            - name: Run coverage
              run: make coverage
            - name: "Upload coverage to Codecov"
              uses: codecov/codecov-action@v1
              with:
                  fail_ci_if_error: true
